# Generated by Django 6.1.1 on 2026-09-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='messages',
            field=models.JSONField(default=list),
        ),
    ]
